version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    commit-message:
      prefix: "deps"
      prefix-development: "devDeps"
      include: "scope"
    reviewers:
      - "DTrombett"
